global:
  resolve_timeout: 5m
  slack_api_url: "{{ slack_webhook_url }}"

route:
  group_by: [alertname, instance, job]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: slack-notifications
  routes:
    - match:
        severity: critical
      receiver: slack-critical
    - match:
        severity: warning
      receiver: slack-warning

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        channel: '#devopsnotifications'
        title: '{{ if eq .Status "firing" }}🔴 ALERT{{ else }}🟢 RESOLVED{{ end }}: {{ .CommonLabels.alertname }}'
        text: |
          {{ if eq .Status "firing" }}*SYSTEM ALERT*{{ else }}*SYSTEM RECOVERED*{{ end }}

          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}

          *⏰ Incident Details:*
          • Started: {{ .StartsAt }}
          • Status: {{ .Status | toUpper }}

          *🔍 Technical Information:*
          • System: {{ .Labels.instance }}
          • Job: {{ .Labels.job }}
          • Severity: {{ .Labels.severity }}

          *👥 Impact Assessment:*
          • Users affected: {{ if eq .Labels.job "blackbox_http" }}Website visitors{{ else }}Service users{{ end }}

          *👥 Team to Notify:* @devops-team
          {{ end }}
        icon_emoji: '{{ if eq .Status "firing" }}:red_circle:{{ else }}:green_circle:{{ end }}'

  - name: 'slack-critical'
    slack_configs:
      - send_resolved: true
        channel: '#devopsnotifications'
        title: '{{ if eq .Status "firing" }}🔴 CRITICAL{{ else }}🟢 RESOLVED{{ end }}: {{ .CommonLabels.alertname }}'
        text: |
          {{ if eq .Status "firing" }}*CRITICAL SYSTEM ALERT*{{ else }}*SYSTEM RECOVERED*{{ end }}

          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}

          *⏰ Incident Details:*
          • Started: {{ .StartsAt }}
          • Status: {{ .Status | toUpper }}

          *🔍 Technical Information:*
          • System: {{ .Labels.instance }}
          • Job: {{ .Labels.job }}
          {{ if eq .Labels.job "blackbox_http" }}• Error: Connection failed
          • HTTP Status: No response{{ end }}

          *👥 Impact Assessment:*
          • Severity: Critical
          • User Impact: {{ if eq .Labels.job "blackbox_http" }}All website users affected{{ else }}Service degradation{{ end }}

          *🚨 Attention:* <@U08K2M1ERS5>
          {{ end }}
        icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:white_check_mark:{{ end }}'
        link_names: true

  - name: 'slack-warning'
    slack_configs:
      - send_resolved: true
        channel: '#devopsnotifications'
        title: '{{ if eq .Status "firing" }}⚠️ WARNING{{ else }}🟢 RESOLVED{{ end }}: {{ .CommonLabels.alertname }}'
        text: |
          {{ if eq .Status "firing" }}*WARNING ALERT*{{ else }}*WARNING RESOLVED*{{ end }}

          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}

          *⏰ Incident Details:*
          • Started: {{ .StartsAt }}
          • Status: {{ .Status | toUpper }}

          *🔍 Technical Information:*
          • System: {{ .Labels.instance }}
          • Job: {{ .Labels.job }}
          {{ if eq .Labels.alertname "SlowResponseTime" }}• Response Time: {{ if eq .Labels.job "blackbox_http" }}Slow{{ end }}{{ end }}
          {{ if eq .Labels.alertname "SSLCertExpiringSoon" }}• Certificate Expires: Soon{{ end }}
          {{ if eq .Labels.alertname "HighCPULoad" }}• CPU Load: High{{ end }}
          {{ if eq .Labels.alertname "HighMemoryLoad" }}• Memory Use: High{{ end }}
          {{ if eq .Labels.alertname "HighDiskUsage" }}• Disk Usage: High{{ end }}

          *👥 Impact Assessment:*
          • Severity: Warning
          • User Impact: Potential performance degradation

          *💡 Recommended Actions:*
          {{ if eq .Labels.alertname "SlowResponseTime" }}Check database queries or high backend resource usage.{{ else if eq .Labels.alertname "SSLCertExpiringSoon" }}Renew SSL certificate before expiration.{{ else if eq .Labels.alertname "HighCPULoad" }}Identify CPU-intensive processes and optimize.{{ else if eq .Labels.alertname "HighMemoryLoad" }}Check for memory leaks or increase available memory.{{ else if eq .Labels.alertname "HighDiskUsage" }}Clean up disk space or expand storage.{{ end }}

          *🚨 Attention:* <@U08K2M1ERS5>
          {{ end }}
        icon_emoji: '{{ if eq .Status "firing" }}:warning:{{ else }}:white_check_mark:{{ end }}'
        link_names: true