---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Restart Alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Restart Blackbox Exporter
  ansible.builtin.systemd:
    name: blackbox-exporter
    state: restarted

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: Restart td-agent
  become: true
  systemd:
    name: td-agent
    state: restarted

- name: Restart Loki
  become: true
  systemd:
    name: loki
    state: restarted

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes
